from .pipeline_cogvideox_fun import CogVideoX_Fun_Pipeline
from .pipeline_cogvideox_fun_control import CogVideoX_Fun_Pipeline_Control
from .pipeline_cogvideox_fun_inpaint import CogVideoX_Fun_Pipeline_Inpaint
from .pipeline_wan_fun import WanFunPipeline
from .pipeline_wan_fun_inpaint import WanFunInpaintPipeline

WanPipeline = WanFunPipeline
WanI2VPipeline = WanFunInpaintPipeline